In [116]:
import pandas as pd
import numpy as np

In [117]:
UPP = pd.read_csv('upp.csv', sep = ';' ,encoding = "latin 1")

In [118]:
UPP.describe()

,cod_upp,ano,mes,hom_doloso,lesao_corp_morte,latrocinio,hom_por_interv_policial,tentat_hom,lesao_corp_dolosa,estupro,...,armas_apreendidas,cump_mandado_prisao,ocorr_flagrante,ameaca,pessoas_desaparecidas,encontro_cadaver,encontro_ossada,pol_militares_mortos_serv,pol_civis_mortos_serv,registro_ocorrencias
count,5472.000000,5472.000000,5472.000000,5472.000000,5472.000000,5472.000000,5472.000000,5472.000000,5472.000000,5472.000000,...,5472.000000,5472.000000,5472.000000,5472.000000,5472.000000,5472.000000,5472.000000,5472.000000,5472.000000,5472.000000
mean,19.500000,2012.500000,6.500000,0.226608,0.004751,0.003655,0.186952,1.056287,5.087354,0.267178,...,0.785270,0.475512,2.271382,3.459430,0.417946,0.029788,0.001279,0.009686,0.000365,30.782346
std,10.966858,3.452368,3.452368,0.638869,0.071381,0.063308,0.656192,2.751337,6.487059,0.664721,...,1.881069,1.441018,3.839210,4.607477,0.823166,0.183462,0.044821,0.110239,0.019116,35.124152
min,1.000000,2007.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,10.000000,2009.750000,3.750000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,...,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,11.000000
50%,19.500000,2012.500000,6.500000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,0.000000,...,0.000000,0.000000,1.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,21.000000
75%,29.000000,2015.250000,9.250000,0.000000,0.000000,0.000000,0.000000,1.000000,7.000000,0.000000,...,1.000000,0.000000,3.000000,5.000000,1.000000,0.000000,0.000000,0.000000,0.000000,36.000000
max,38.000000,2018.000000,12.000000,10.000000,2.000000,2.000000,12.000000,39.000000,71.000000,11.000000,...,57.000000,27.000000,49.000000,50.000000,8.000000,2.000000,2.000000,3.000000,1.000000,328.000000

In [119]:
UPP.index.values

array([   0,    1,    2, ..., 5469, 5470, 5471], dtype=int64)

In [120]:
UPP.columns = UPP.columns.str.strip().str.lower().str.replace(' ', '_').str.replace('(', '').str.replace(')', '')
UPP.columns

Index(['cod_upp', 'upp', 'ano', 'mes', 'hom_doloso', 'lesao_corp_morte',
       'latrocinio', 'hom_por_interv_policial', 'tentat_hom',
       'lesao_corp_dolosa', 'estupro', 'hom_culposo', 'lesao_corp_culposa',
       'roubo_comercio', 'roubo_residencia', 'roubo_veiculo', 'roubo_carga',
       'roubo_transeunte', 'roubo_em_coletivo', 'roubo_banco',
       'roubo_cx_eletronico', 'roubo_celular', 'roubo_conducao_saque',
       'total_roubos', 'furto_veiculos', 'total_furtos', 'sequestro',
       'extorsao', 'sequestro_relampago', 'estelionato', 'apreensao_drogas',
       'recuperacao_veiculos', 'armas_apreendidas', 'cump_mandado_prisao',
       'ocorr_flagrante', 'ameaca', 'pessoas_desaparecidas',
       'encontro_cadaver', 'encontro_ossada', 'pol_militares_mortos_serv',
       'pol_civis_mortos_serv', 'registro_ocorrencias'],
      dtype='object')

In [121]:
UPP['mes'] = UPP['mes'].astype(int)

In [122]:
months_map = {1: 'JAN', 2: 'FEV', 3: 'MAR', 4: 'ABR', 5: 'MAI', 6:'JUN', 7:'JUL', 8: 'AGO', 9: 'SET', 10: 'OUT', 11: 'NOV', 12: 'DEZ'}
import calendar

d = dict(enumerate(calendar.month_abbr))
UPP['mes'] = UPP['mes'].map(d)
UPP

,cod_upp,upp,ano,mes,hom_doloso,lesao_corp_morte,latrocinio,hom_por_interv_policial,tentat_hom,lesao_corp_dolosa,...,armas_apreendidas,cump_mandado_prisao,ocorr_flagrante,ameaca,pessoas_desaparecidas,encontro_cadaver,encontro_ossada,pol_militares_mortos_serv,pol_civis_mortos_serv,registro_ocorrencias
0,1,Santa Marta,2007,Jan,0,0,0,0,0,1,...,2,1,0,0,0,0,0,0,0,11
1,2,Cidade de Deus,2007,Jan,3,0,0,0,1,18,...,7,2,11,7,2,0,0,0,0,98
2,3,Batam,2007,Jan,0,0,0,0,0,4,...,0,0,0,1,0,0,0,0,0,19
3,4,ChapÃ©u Mangueira / BabilÃ´nia,2007,Jan,0,0,0,0,0,1,...,0,2,0,1,0,0,0,0,0,9
4,5,PavÃ£o-PavÃ£ozinho,2007,Jan,0,0,0,0,0,4,...,0,0,0,1,1,0,0,0,0,12
5,6,Tabajaras,2007,Jan,0,0,0,0,0,2,...,1,0,0,1,0,0,0,0,0,6
6,7,ProvidÃªncia,2007,Jan,1,0,0,0,0,6,...,5,0,0,8,0,0,0,0,0,31
7,8,Borel,2007,Jan,1,0,0,0,0,2,...,2,1,0,0,0,0,0,0,0,17
8,9,Formiga,2007,Jan,2,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,6
9,10,AndaraÃ­,2007,Jan,0,0,0,3,0,1,...,2,0,1,4,0,0,0,0,0,32
10,11,Salgueiro,2007,Jan,0,0,0,0,0,7,...,0,0,1,8,1,0,0,0,0,42
11,12,Turano,2007,Jan,0,0,0,0,0,1,...,0,0,0,2,1,0,0,0,0,20
12,13,SÃ£o JoÃ£o / Matriz / Queto,2007,Jan,0,0,0,0,1,0,...,1,0,1,1,0,0,0,0,0,7
13,14,Coroa / Fallet / Fogueteiro,2007,Jan,1,0,0,0,1,2,...,5,0,0,1,0,0,0,0,0,15
14,15,Escondidinho / Prazeres,2007,Jan,1,0,0,0,0,1,...,0,0,0,1,2,0,0,0,0,8
15,16,SÃ£o Carlos,2007,Jan,0,0,0,0,0,13,...,6,0,0,7,1,0,0,0,0,36
16,17,Mangueira,2007,Jan,1,0,0,0,0,5,...,5,0,0,5,0,0,0,0,0,31
17,18,Macacos,2007,Jan,2,0,0,0,0,1,...,1,0,1,2,1,0,0,0,0,51
18,19,Vidigal,2007,Jan,0,0,0,0,0,0,...,1,0,1,1,0,0,0,0,0,6
19,20,Nova BrasÃ­lia,2007,Jan,0,0,0,0,0,3,...,0,0,0,1,0,0,0,0,0,6
20,21,Fazendinha,2007,Jan,2,0,0,0,0,2,...,1,0,1,1,0,0,0,0,0,16
21,22,Adeus / Baiana,2007,Jan,0,0,0,0,0,1,...,1,0,0,0,2,1,0,0,0,18
22,23,AlemÃ£o,2007,Jan,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,2
23,24,Chatuba,2007,Jan,0,0,0,0,0,3,...,0,0,0,1,0,0,0,0,0,12
24,25,FÃ© / Sereno,2007,Jan,0,0,0,0,0,1,...,0,0,0,1,0,0,0,0,0,1
25,26,Parque ProletÃ¡rio,2007,Jan,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,5
26,27,Vila Cruzeiro,2007,Jan,1,0,0,3,0,6,...,3,0,3,1,3,0,0,0,0,21
27,28,Rocinha,2007,Jan,0,0,0,0,0,2,...,2,0,1,2,0,0,0,0,0,11
28,29,Jacarezinho,2007,Jan,0,0,0,0,1,2,...,13,0,1,7,1,0,0,0,0,51
29,30,Manguinhos,2007,Jan,1,0,0,0,0,0,...,2,0,2,6,0,0,0,0,0,19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5442,9,Formiga,2018,Dec,0,0,0,0,0,1,...,0,0,2,1,0,0,0,0,0,6
5443,10,AndaraÃ­,2018,Dec,0,0,0,0,0,2,...,1,1,3,1,0,0,0,0,0,16
5444,11,Salgueiro,2018,Dec,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,7
5445,12,Turano,2018,Dec,0,0,0,0,0,1,...,0,0,0,1,0,0,0,0,0,11
5446,13,SÃ£o JoÃ£o / Matriz / Queto,2018,Dec,0,0,0,0,0,1,...,0,0,0,5,0,0,0,0,0,20
5447,14,Coroa / Fallet / Fogueteiro,2018,Dec,0,0,0,1,0,2,...,1,0,0,2,0,0,0,0,0,15
5448,15,Escondidinho / Prazeres,2018,Dec,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,6
5449,16,SÃ£o Carlos,2018,Dec,0,0,0,0,1,4,...,0,0,0,4,0,0,0,0,0,24
5450,17,Mangueira,2018,Dec,0,0,0,0,0,3,...,0,0,4,2,2,0,0,0,0,35
5451,18,Macacos,2018,Dec,0,0,0,0,0,3,...,1,1,1,0,0,0,0,0,0,24
5452,19,Vidigal,2018,Dec,0,0,0,0,5,3,...,1,0,3,1,1,0,0,0,0,27
5453,20,Nova BrasÃ­lia,2018,Dec,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,13
5454,21,Fazendinha,2018,Dec,0,0,0,0,3,1,...,0,0,0,0,1,0,0,0,0,19
5455,22,Adeus / Baiana,2018,Dec,2,0,0,0,0,3,...,0,0,2,1,0,0,0,0,0,24
5456,23,AlemÃ£o,2018,Dec,0,0,0,0,0,3,...,0,0,0,0,0,0,0,0,0,6
5457,24,Chatuba,2018,Dec,0,0,0,0,0,3,...,1,0,0,0,0,0,0,0,0,20
5458,25,FÃ© / Sereno,2018,Dec,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,4
5459,26,Parque ProletÃ¡rio,2018,Dec,0,0,0,0,0,1,...,0,0,0,0,1,0,0,0,0,15
5460,27,Vila Cruzeiro,2018,Dec,0,0,0,1,0,1,...,1,0,0,1,0,0,0,0,0,19
5461,28,Rocinha,2018,Dec,0,0,0,0,0,7,...,0,0,2,6,0,0,0,0,0,79
5462,29,Jacarezinho,2018,Dec,4,1,0,1,5,4,...,1,1,5,5,1,0,0,0,0,77
5463,30,Manguinhos,2018,Dec,0,0,0,0,0,3,...,0,0,0,3,0,0,0,0,0,17
5464,31,Barreira do Vasco / Tuiuti,2018,Dec,0,0,0,0,3,7,...,0,4,9,7,0,0,0,0,0,114
5465,32,Caju,2018,Dec,0,0,0,0,0,3,...,0,1,0,3,0,0,0,0,0,12
5466,33,Cerro-CorÃ¡,2018,Dec,0,0,0,0,0,2,...,0,0,1,1,0,0,0,0,0,5
5467,34,ArarÃ¡ / Mandela,2018,Dec,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,12
5468,35,Lins,2018,Dec,1,0,0,0,0,10,...,0,0,0,4,0,0,0,0,0,41
5469,36,Camarista MÃ©ier,2018,Dec,0,0,0,0,0,7,...,0,0,1,7,0,0,0,0,0,46
5470,37,Mangueirinha,2018,Dec,1,0,0,1,2,7,...,2,0,1,2,0,0,0,0,0,46
5471,38,Vila Kennedy,2018,Dec,2,0,0,1,2,7,...,3,2,7,11,1,0,0,0,0,200

In [123]:
UPP = UPP.groupby(['upp', 'ano', 'mes']).sum()
UPP

                         cod_upp  hom_doloso  lesao_corp_morte  latrocinio  \
upp            ano  mes
Adeus / Baiana 2007 Apr       22           0                 0           0
                    Aug       22           0                 0           0
                    Dec       22           0                 0           0
                    Feb       22           0                 0           0
                    Jan       22           0                 0           0
                    Jul       22           0                 0           0
                    Jun       22           2                 0           0
                    Mar       22           0                 0           0
                    May       22           1                 0           0
                    Nov       22           1                 0           0
                    Oct       22           0                 0           0
                    Sep       22           0                 0           0
               2008 Apr       22           0                 0           0
                    Aug       22           0                 0           0
                    Dec       22           0                 0           0
                    Feb       22           1                 0           0
                    Jan       22           0                 0           0
                    Jul       22           0                 0           0
                    Jun       22           0                 0           0
                    Mar       22           0                 0           0
                    May       22           0                 0           0
                    Nov       22           0                 0           0
                    Oct       22           0                 0           0
                    Sep       22           0                 0           0
               2009 Apr       22           0                 0           0
                    Aug       22           0                 0           0
                    Dec       22           0                 0           0
                    Feb       22           0                 0           0
                    Jan       22           0                 0           0
                    Jul       22           0                 0           0
...                          ...         ...               ...         ...
Vila Kennedy   2016 Jun       38           1                 0           0
                    Mar       38           5                 0           0
                    May       38           0                 0           0
                    Nov       38           1                 0           0
                    Oct       38           1                 2           0
                    Sep       38           0                 0           0
               2017 Apr       38           1                 0           0
                    Aug       38           2                 0           0
                    Dec       38           1                 0           0
                    Feb       38           1                 0           0
                    Jan       38           3                 0           1
                    Jul       38           0                 0           0
                    Jun       38           2                 0           0
                    Mar       38           1                 0           0
                    May       38           2                 0           0
                    Nov       38           1                 0           0
                    Oct       38           1                 0           0
                    Sep       38           2                 0           0
               2018 Apr       38           0                 0           0
                    Aug       38           0                 0           0
                    Dec       38           2                 0           0
                    Feb       38           0                 0           0
                    Jan       38           1                 0           0
                    Jul       38           0                 0           0
                    Jun       38           3                 0           0
                    Mar       38           2                 0           0
                    May       38           1                 0           0
                    Nov       38           2                 0           0
                    Oct       38           1                 0           0
                    Sep       38           2                 0           0

                         hom_por_interv_policial  tentat_hom  \
upp            ano  mes
Adeus / Baiana 2007 Apr                        0           0
                    Aug                        0           0
                    Dec                        0           2
                    Feb                        0           0
                    Jan                        0           0
                    Jul                        0           0
                    Jun                        0           2
                    Mar                        0           0
                    May                        0           0
                    Nov                        4           5
                    Oct                        0           0
                    Sep                        0           0
               2008 Apr                        0           0
                    Aug                        0           0
                    Dec                        0           0
                    Feb                        0           0
                    Jan                        0           0
                    Jul                        0           0
                    Jun                        0           1
                    Mar                        0           0
                    May                        0           0
                    Nov                        0           0
                    Oct                        0           0
                    Sep                        2           0
               2009 Apr                        0           0
                    Aug                        0           0
                    Dec                        0           0
                    Feb                        0           0
                    Jan                        0           1
                    Jul                        0           0
...                                          ...         ...
Vila Kennedy   2016 Jun                        0           0
                    Mar                        0           2
                    May                        0           2
                    Nov                        0           0
                    Oct                        0           0
                    Sep                        0           2
               2017 Apr                        1           3
                    Aug                        0           0
                    Dec                        2           6
                    Feb                        0           0
                    Jan                        1          11
                    Jul                        1           8
                    Jun                        0          12
                    Mar                        3           7
                    May                        0          11
                    Nov                        4           4
                    Oct                        0          17
                    Sep                        0           3
               2018 Apr                        1           2
                    Aug                        1           1
                    Dec                        1           2
                    Feb                        0           0
                    Jan                        0           7
                    Jul                        1          10
                    Jun                        0           5
                    Mar                        0           1
                    May                        0           3
                    Nov                        4           2
                    Oct                        4           4
                    Sep                        0           4

                         lesao_corp_dolosa  estupro  hom_culposo  \
upp            ano  mes
Adeus / Baiana 2007 Apr                  2        0            0
                    Aug                  0        0            0
                    Dec                  1        0            0
                    Feb                  4        0            0
                    Jan                  1        0            0
                    Jul                  2        0            0
                    Jun                  1        0            0
                    Mar                  1        0            0
                    May                  3        0            0
                    Nov                  3        0            0
                    Oct                  1        0            0
                    Sep                  4        0            0
               2008 Apr                  1        0            0
                    Aug                  3        0            0
                    Dec                  2        0            0
                    Feb                  1        0            0
                    Jan                  1        0            0
                    Jul                  2        0            0
                    Jun                  1        0            0
                    Mar                  2        0            0
                    May                  3        0            0
                    Nov                  1        1            0
                    Oct                  6        0            0
                    Sep                  1        0            0
               2009 Apr                  5        0            0
                    Aug                  1        0            0
                    Dec                  1        0            0
                    Feb                  1        0            0
                    Jan                  4        0            0
                    Jul                  4        0            0
...                                    ...      ...          ...
Vila Kennedy   2016 Jun                  9        0            0
                    Mar                  4        0            0
                    May                  3        1            3
                    Nov                 17        1            1
                    Oct                 26        0            1
                    Sep                 10        3            0
               2017 Apr                 13        0            0
                    Aug                 21        0            0
                    Dec                 19        0            0
                    Feb                  9        0            0
                    Jan                 14        0            1
                    Jul                 12        1            1
                    Jun                 18        0            2
                    Mar                  9        4            1
                    May                 12        0            0
                    Nov                 11        2            1
                    Oct                 18        2            0
                    Sep                 18        2            0
               2018 Apr                 13        3            0
                    Aug                  5        1            0
                    Dec                  7        1            2
                    Feb                  6        1            0
                    Jan                 21        1            1
                    Jul                 12        1            1
                    Jun                  5        2            0
                    Mar                 19        2            0
                    May                 20        1            0
                    Nov                 18        1            2
                    Oct                  7        0            0
                    Sep                 20        0            0

                         lesao_corp_culposa  ...  armas_apreendidas  \
upp            ano  mes                      ...
Adeus / Baiana 2007 Apr                   0  ...                  0
                    Aug                   0  ...                  1
                    Dec                   0  ...                  0
                    Feb                   0  ...                  2
                    Jan                   0  ...                  1
                    Jul                   0  ...                  0
                    Jun                   0  ...                  0
                    Mar                   0  ...                  0
                    May                   0  ...                  0
                    Nov                   0  ...                  9
                    Oct                   0  ...                  0
                    Sep                   0  ...                  0
               2008 Apr                   0  ...                  0
                    Aug                   1  ...                  0
                    Dec                   0  ...                  0
                    Feb                   0  ...                  0
                    Jan                   0  ...                  0
                    Jul                   0  ...                  0
                    Jun                   0  ...                  2
                    Mar                   0  ...                  1
                    May                   0  ...                  0
                    Nov                   0  ...                  0
                    Oct                   0  ...                  0
                    Sep                   1  ...                  1
               2009 Apr                   4  ...                  0
                    Aug                   0  ...                  0
                    Dec                   0  ...                  0
                    Feb                   0  ...                  0
                    Jan                   0  ...                  0
                    Jul                   0  ...                  0
...                                     ...  ...                ...
Vila Kennedy   2016 Jun                   2  ...                  0
                    Mar                   7  ...                  2
                    May                  10  ...                  4
                    Nov                  13  ...                  0
                    Oct                  13  ...                  0
                    Sep                  15  ...                  0
               2017 Apr                   6  ...                  3
                    Aug                  10  ...                  4
                    Dec                   7  ...                  2
                    Feb                   4  ...                  2
                    Jan                  12  ...                  5
                    Jul                  27  ...                  8
                    Jun                   8  ...                  7
                    Mar                   9  ...                  6
                    May                  21  ...                  3
                    Nov                  15  ...                 15
                    Oct                  14  ...                  0
                    Sep                   3  ...                  1
               2018 Apr                   9  ...                  0
                    Aug                   6  ...                  3
                    Dec                   8  ...                  3
                    Feb                   5  ...                  0
                    Jan                  10  ...                  2
                    Jul                  12  ...                  6
                    Jun                   5  ...                  2
                    Mar                   6  ...                  1
                    May                  11  ...                  2
                    Nov                  12  ...                  5
                    Oct                  12  ...                  6
                    Sep                  12  ...                  2

                         cump_mandado_prisao  ocorr_flagrante  ameaca  \
upp            ano  mes
Adeus / Baiana 2007 Apr                    0                0       1
                    Aug                    0                0       0
                    Dec                    0                0       0
                    Feb                    0                1       5
                    Jan                    0                0       0
                    Jul                    0                0       1
                    Jun                    0                0       4
                    Mar                    0                2       1
                    May                    0                0       0
                    Nov                    0                1       0
                    Oct                    0                1       0
                    Sep                    0                0       2
               2008 Apr                    0                0       4
                    Aug                    0                0       1
                    Dec                    0                0       3
                    Feb                    0                0       0
                    Jan                    0                0       1
                    Jul                    0                0       3
                    Jun                    0                0       1
                    Mar                    0                0       1
                    May                    0                0       1
                    Nov                    0                0       0
                    Oct                    0                0       4
                    Sep                    0                0       0
               2009 Apr                    0                1       1
                    Aug                    0                0       0
                    Dec                    0                0       0
                    Feb                    0                0       0
                    Jan                    0                1       4
                    Jul                    0                0       2
...                                      ...              ...     ...
Vila Kennedy   2016 Jun                    3                5       4
                    Mar                    3               10      12
                    May                    5               26       4
                    Nov                   10                9       7
                    Oct                    8                8      11
                    Sep                   15                8      15
               2017 Apr                    9               16       7
                    Aug                   27               18      12
                    Dec                   23               10       9
                    Feb                    7               10       9
                    Jan                    7               21       6
                    Jul                   13               16      16
                    Jun                   12               20       7